
build_binary:
  stage: build
  tags: [amd64]
  image: "ubuntu:24.04"
  script:
    - apt-get update
    - apt-get install -y make musl-dev musl-tools musl curl gcc
    - export CARGO_HOME=/etc/skel/.cargo
    - export RUSTUP_HOME=/etc/skel/.rustup
    - curl -fsSL https://sh.rustup.rs | sh -s -- -y --default-toolchain=stable --profile=minimal
    - source $CARGO_HOME/env
    - rustup component add rustfmt clippy
    - rustup target add x86_64-unknown-linux-musl
    - cargo build

stages:
 - build
